### PR TITLE
Add instructions and tweak tts.pro file for osx.

### PR DESCRIPTION
**Pull request by jimmyw**
Builds and runs, have not managed to test it yet.

### CODE REVIEW

**Comment by iforce2d** [comment]
I think that last line: 
unix:!macx += -lX11 -lOpenGL

... should be like this:
unix:!macx:LIBS += -lX11 -lGL

Can you check if that works on Mac?

**Comment by jimmyw** [comment]
Works! updated my branch...

Good find!

**Comment by iforce2d** [comment]
Thanks Jimmy! Do you have an arduino around to check with? Even if you don't have any of the other parts of the test stand ready, you should be able to check whether: 
1. the serial ports are enumerated correctly and the arduino shows up
2. the arduino can be connected to
3. the OpenGL display is working correctly

For 1 just click 'Update list' after connecting the arduino and the device should then show up in the combobox list. 
For 2 click 'Open' and you should see "Opened port xxx" in the log panel and the status bar will change to "Connected to xxx".
For 3, after opening the connection you should see the colored text display showing in the main panel, eg "Throttle 1000us", "Thrust 0 g"... etc. 

You don't need to have the correct sketch on the arduino, it will connect regardless (but of course, no useful communication will be found).

**Comment by jimmyw** [comment]
Hi!

I uploaded it to Arduino UNO that i had laying around, it emurated fine. I managed to connect to it, and got some data rendered back.

I have a loadsensor same model you are using, so im going to see if i can hook it up.

/J

screen shot 2016-11-18 at 22 56 40

**Comment by iforce2d** [comment]
Great, it looks like the connection is working ok. If the graphical view is refreshing quickly and smoothly (50-60fps) and with no pauses or stuttering, then it should be good to go.

**Comment by jimmyw** [comment]
Yes, can confirm that i got the load cell working now :)

Tomorrow i might have time to try some motors!

Thanks!

**Pull request merged**
